### ISSUE TITLE
Improve the test "test_fiat_adapter_measures"

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares-research/FloodAdapt#182]
### Kind of request

Changing existing functionality

### Enhancement Description

In the test 'test_fiat_adapter_measures' the assert for raising properties does not do much, it just checks whether the heights are the same or lower but it does not test whether the ground floors were raised correctly. The test passed at one point but the ground floor heights were not yet correct

### Task list

* Improve test to check for correctness
* Re-test with the example from Frederique where it did not raise correctly

**Comment by frederique-hub** [comment]
I'll look into this once @panosatha and I have sat together to update FloodAdapt to the latest changes in HydroMT FIAT
