### ISSUE TITLE
Determine length of roads with flood inundation greater than a specified threshold

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares-research/FloodAdapt#270]
### Kind of request

Adding new functionality

### Enhancement Description

We need to know the length of road associated with each road 'object' in the exposure data in order to complete our infographic, which gives information about the length of roads that are inundated above some threshold (e.g. 0.5 feet). 

### Task list

* Decide where the functionality should live to determine the length of road per road object (part of standard Delft-FIAT output, something that FloodAdapt backend does?)
* Decide where the information should be stored (in the Delft-FIAT output? In a separate file?)

**Comment by frederique-hub** [comment]
We are now implementing the roads in HydroMT-FIAT and I think it would be best if: 

- We save the road length in the exposure data
- We compute the lengths of road inundated above a certain threshold with the FIAT toolbox and directly input into the infographic (or also save it as a small csv file)
