### ISSUE TITLE
Metrics comparison table - difficult to find the scenario for 'deletion' from the table

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares-research/FloodAdapt#275]
### Kind of request

Changing existing functionality

### Enhancement Description

Right now if you add a bunch of scenarios in the 'compare - table' tab, and you want to delete one, you can't just select the column and click delete. You have to find the scenario again in the scenario select window. Would be better if you could just select it in the comparison window and click delete.

### Task list

* Figure out how hard it is to select a column in the table and then click delete
* Implement if not too difficult

**Comment by dladrichem** [comment]
This one waits for a PR in Guitares. Review needed from Maarten
