### ISSUE TITLE
Metrics comparison table - order of metrics is different than in the configuration file

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares-research/FloodAdapt#276]
### Kind of request

Changing existing functionality

### Enhancement Description

The order of the metrics in the comparison table should be the same as the order given in the configuration file. In the "output" tab the order IS in the order in the configuration file, but in the metrics comparison table it isn't.

### Task list

* Review how the order is determined for the "output" tab
* Replicate that for the order in the compare - table tab.

**Comment by dladrichem** [comment]
Linked to #275

**Comment by dladrichem** [comment]
This one waits for a PR 51 in Guitares. Review needed from Maarten
