### ISSUE TITLE
objects used in a scenario that has been run should not be editable

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#283]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Editing events, projections, measures, and strategies that are used in scenarios that have already been run is allowed. That means that the information between the scenario output and the inputs can be incosistent. 

### Current behaviour

Currently, you can edit events, projections, measures, and strategies that are used in scenarios that have already been run.

### Desired behaviour

The same warning that is currently implemented for the delete method should be implemented for the edit method.

### Task list

TBD

**Comment by dladrichem** [comment]
A lot of unit tests are nog running right now. Since this issue requires some refactoring, first make sure the unit tests are running
