### ISSUE TITLE
If you have a 'foreign' folder in the output folder, no scenarios can be run

### ISSUE THREAD

**Issue by kathrynroscoe** [Deltares-research/FloodAdapt#290]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

I zipped a few output folders to give to a student. So I now have a folder in my output folder called "Hurricane_Ian_Scenarios". when I tried to run a scenario, I got the error message that the scenario couldn't be run. The error message in VS Code was:
[Errno 2] No such file or directory: 'D:\\_CODE\\FloodAdapt-GUI\\Database\\charleston_practitionerGroup_Oct2023\\input\\scenarios\\Hurricane_Ian_scenarios.zip\\Hurricane_Ian_scenarios.zip.toml'

So it is checking that every output folder has associated input folders. 

![image](https://github.com/Deltares-research/FloodAdapt/assets/79269966/2d68f442-b373-4dcb-8740-561a869bef5b)

### Current behaviour

If there's a 'foreign' folder in the output folder, scenarios will not run.

### Desired behaviour

If there is a foreign folder in the output folder, FloodAdapt will recognize it as foreign (doesn't match any of the scenario names) and ignore it. 

### Task list

* Decide who picks this issue up
* Identify the code that is doing this check before running a scenario
* Add in an exception for folder names that do not coincide with a scenario name

**Comment by panosatha** [comment]
I am not sure if really see this as an issue. Why should we allow for having other folrders in the output?

**Comment by kathrynroscoe** [comment]
Well it is allowed haha. I zipped some output folders to share with a student and left the zip file in the folder and then FloodAdapt wouldn’t run.

Sent from my phone
________________________________

**Comment by panosatha** [comment]
yeah, that's what I am saying. There tons of things that can go wrong if someone starts to delete or add files in the folder structure. Should we do something for all these potential scenarios? I think we should just make clear that a user should not mess up with the file and folder structure.

**Comment by dladrichem** [comment]
Solved by adding more documentation
