### ISSUE TITLE
New development area aggregation handling

### ISSUE THREAD

**Issue by panosatha** [Deltares-research/FloodAdapt#318]
### Kind of request

None

### Enhancement Description

Currently the way the new developement area is implemented in HydroMT-FIAT is to throw an error when the polygons of the new areas, overlap with more than one aggregation areas.
The correct behaviour would be that the composite areas are divided to smaller parts by uing the aggregation areas, so that is smaller part of the composite areas, fall only under a single aggregation area.

### Task list

- [x] Change code in HydroMT-FIAT 
- [x] Test that it works as expected in FloodAdapt

**Comment by savente93** [comment]
This issue is marked as belonging to the march milestone. Is it still relevant? if so, should we move it to the current milestone? if not, can we remove/close it?

**Comment by Santonia27** [comment]
I sent a new PR to Panos last week, I dont know how relevant it is/when he has time to review it
