### ISSUE TITLE
Reuse dbs_controller function to get obs_points in SFINCS adapter

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#320]
### Kind of request

None

### Enhancement Description

Reuse dbs_controller function to get obs_points in SFINCS adapter, see comment in PR # https://github.com/Deltares-research/FloodAdapt/pull/308 

### Task list

Reuse dbs_controller function to get obs_points in SFINCS adapter

**Comment by dladrichem** [comment]
This is already part of other refactors
