### ISSUE TITLE
Update pydantic v1 deprecated syntax to pydantic v2

### ISSUE THREAD

**Issue by LuukBlom** [Deltares-research/FloodAdapt#350]
Since we just upgraded to a newer hydromt version that uses pydantic 2.x instead of 1.x, we should move to update the deprecated syntax from 1.x relatively soon.
examples of stuff that needs upgrading: 

- The method "parse_obj" in class "BaseModel" is deprecated
  The `parse_obj` method is deprecated; use `model_validate` instead

- The method "dict" in class "BaseModel" is deprecated
  The `dict` method is deprecated; use `model_dump` instead.

**Comment by dladrichem** [comment]
Part of refactoring the pydantic version should also be adding validators to all conditional variables (optional once that are not truely optional) and making more specific models. Then also use these new models created using these variables (i.e. unitfulheigth)

**Comment by dladrichem** [comment]
Switch to pydantic V2 is made. Adding validators should be an ongoing process
