### ISSUE TITLE
Include rainfall in spw files

### ISSUE THREAD

**Issue by GundulaW** [Deltares-research/FloodAdapt#392]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

Rainfall is never added in spiderweb files

### Current behaviour

Rainfall is never added in spiderweb files

### Desired behaviour

Add rainfall if rainfall_source is track

### Task list

fix

**Comment by dladrichem** [comment]
Check if it is aleady fixed. If so, close issue

**Comment by GundulaW** [comment]
Left with rainfall from track, right without
![Image](https://github.com/Deltares-research/FloodAdapt/assets/74292006/656ef4ce-10fe-4cb9-9e0c-73992744c8be)
