### ISSUE TITLE
Water level offset should not be included in synthetic events

### ISSUE THREAD

**Issue by LuukBlom** [Deltares-research/FloodAdapt#410]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

if you make an event with an offshore model, floodadapt will always add the water level offset to the overland surge & tide, even when you have specified a synthetic overland model (which should not have this addition)

### Current behaviour

always add water level offset

### Desired behaviour

Offshore model with historic gauges run?
Needs water level offset since the historic gauges need to be corrected for slr.
Otherwise it does not need it and will just use whatever you have provided in the overland model

### Task list

events refactor

**Comment by dladrichem** [comment]
@kathrynroscoe: This also shouldn't be added for historical nearshore

**Comment by dladrichem** [comment]
Gundula will discuss this with Kathryn

**Comment by GundulaW** [comment]
I made an overview of where the water level offset is appliedhttps://deltares-my.sharepoint.com/:w:/g/personal/gundula_winter_deltares_nl/Edwlsl8NDJhBsgilMw5yBxMBpZxYyqBXDrm2JknvtgW2kQ?e=I74NAp
