### ISSUE TITLE
Case sensitivity & consistency folder structure

### ISSUE THREAD

**Issue by WOTrompDeltares** [Deltares-research/FloodAdapt#429]
### FloodAdapt version checks

- [X] I have checked that this issue has not already been reported.
- [X] I have checked that this bug exists on the latest version of FloodAdapt.

### Reproducible Example

https://github.com/interTwin-eu/DT-flood/blob/main/Notebooks/LaunchWorkflow.ipynb
https://github.com/interTwin-eu/DT-flood/blob/main/DT_flood/utils/fa_scenario_utils.py

See traceback when Projections folder uses capital P:
![image](https://github.com/Deltares-research/FloodAdapt/assets/142423474/fc875e33-1154-47f7-b803-6bfe0920ee90)

See traceback when projections folder uses lower case p:
![image](https://github.com/Deltares-research/FloodAdapt/assets/142423474/d7ba1d33-52f6-4b22-b590-40232002d2b6)

### Current behaviour

DirectImpacts.set_socio_economic_change() looks in the "Projections" folder (with capital P). dbs_controllers looks for "projections" (lower case p).
Running on WSL, hence case sensitivity of folder and file names.

### Desired behaviour

Consistent capitalization of folder names. Which one doesn't really matter.

### Task list

Double check hard coded file paths.
To be sure, also other folders in the input folder

**Comment by savente93** [comment]
Marked as done so closing
