### ISSUE TITLE
Make a cleanup and update database script

### ISSUE THREAD

**Issue by dladrichem** [Deltares-research/FloodAdapt#469]
### Kind of request

Adding new functionality

### Enhancement Description

Make a script to update the database for when we make changes to the database
Make a script (or combined) that cleans up the database 

### Task list

- [ ] make script 1
- [ ] Make script 2

**Comment by savente93** [comment]
The attached PR is closed as not necessary because it was implemented elsewhere. @LuukBlom does that mean we can close this issue?
